### ISSUE TITLE
Change icons design.

### ISSUE THREAD

**Issue by ByMykel** [ByMykel/CSGO-ITEMS#11]
![image](https://user-images.githubusercontent.com/38622893/213908876-07fc68c5-fc5d-4f94-ae1b-503a54c3cb5a.png)

The icon's dimensions are all different.

**Comment by Jobayer12** [comment]
@ByMykel 
Could you give me some idea on how to do that and which page I need to do? I will try to solve this issue.
I saw all the "good first issues". Just need some instructions.

Thank You.

**Comment by ByMykel** [comment]
@Jobayer12 I don't know what I want to do with these icons, so until I figured out what I want this issue doesn't need help.
